#!/bin/bash
# Helper script to download pre-built DMG from GitHub Actions
# No Xcode installation required!

set -e

REPO="frankuyan/SaneSideButtons"
BRANCH="${1:-claude/fix-m4-mac-compatibility-01E9CSANHZe1prNqh8o6TACL}"

echo "📦 SaneSideButtons - Download Pre-built DMG"
echo "============================================="
echo ""
echo "Since building requires Xcode, you can download pre-built DMG files"
echo "from GitHub Actions. The workflows automatically build on every commit."
echo ""
echo "🔗 Quick Links:"
echo ""
echo "   View all builds:"
echo "   https://github.com/${REPO}/actions"
echo ""
echo "   Latest release:"
echo "   https://github.com/${REPO}/releases/latest"
echo ""
echo "📋 To get your DMG:"
echo ""
echo "   1. Open: https://github.com/${REPO}/actions"
echo "   2. Click on the latest 'Build SaneSideButtons' workflow"
echo "   3. Scroll to 'Artifacts' section"
echo "   4. Download 'SaneSideButtons-versioned'"
echo "   5. Unzip and install the DMG"
echo ""
echo "⚡ Or trigger a new build:"
echo ""
echo "   1. Open: https://github.com/${REPO}/actions/workflows/build.yml"
echo "   2. Click 'Run workflow' button"
echo "   3. Select branch: ${BRANCH}"
echo "   4. Click 'Run workflow'"
echo "   5. Wait ~5 minutes"
echo "   6. Download the artifact"
echo ""
echo "📦 Creating a release (with permanent download link):"
echo ""
echo "   git tag v1.5.1"
echo "   git push origin v1.5.1"
echo ""
echo "   This creates a GitHub Release with permanent DMG downloads at:"
echo "   https://github.com/${REPO}/releases"
echo ""
echo "💡 Tip: If you need to build locally, you'll need to install Xcode from:"
echo "   https://apps.apple.com/app/xcode/id497799835"
echo ""
